name: Publish AmneziaWG Release from Artifact

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Имя артефакта (без .zip)'
        required: true
        default: 'amneziawg-24.10.2_aarch64_cortex-a53_mediatek_filogic_6a9e125268c43e0bae8cecb014c8ab03.zip'
      tag_name:
        description: 'Тег для релиза'
        required: true
        default: '24.10.2'
      release_title:
        description: 'Название релиза'
        required: false
        default: 'Сборка AmneziaWG для OpenWRT 24.10.2'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Загрузить артефакт
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Создать релиз и загрузить .ipk
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.release_title }}
          files: |
            *.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
